/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankAccount;

/**
 *
 * @author c3
 */
public class MainFrame extends javax.swing.JFrame {
    private int bt;
    Bank bk;
    public MainFrame() {
        initComponents();
        
        bt=0;
        bk=new Bank();
        acc.setVisible(false);
        acn.setVisible(false);
        am.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        proceed.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acn = new javax.swing.JTextField();
        proceed = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        am = new javax.swing.JTextField();
        acc = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        ai = new javax.swing.JButton();
        tb = new javax.swing.JButton();
        mm = new javax.swing.JButton();
        mba = new javax.swing.JButton();
        cd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("BANK XYZ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ACCOUNT NUMBER :");

        acn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        acn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acnMouseClicked(evt);
            }
        });
        acn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acnActionPerformed(evt);
            }
        });

        proceed.setText("PROCED");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("AMOUNT :");

        am.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });

        acc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        acc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        add.setText("AddAccount");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        ai.setText("AccountInfo");
        ai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aiActionPerformed(evt);
            }
        });

        tb.setText("Total Balance");
        tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbActionPerformed(evt);
            }
        });

        mm.setText("Min and Max");
        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });

        mba.setText("Min Balance A/C");
        mba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbaActionPerformed(evt);
            }
        });

        cd.setText("Credit\\Debit");
        cd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(ai, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(tb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(mba, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(am, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(acc, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mba, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(am, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(proceed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(acc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        if(bt==1){
        boolean flag=true;
        int a=Integer.parseInt(acn.getText());
        for(int i=0;i<Bank.ba.size();i++){
            if (a == Bank.ba.get(i).getAccount())
            {
                acc.setVisible(true);
                acc.setText("Account Already Present");
                flag=false;
                break;
            }
        }
        if(flag==true){
        bk.addAccount(a,Double.parseDouble(am.getText()));
        acc.setVisible(true);
        acc.setText("Account Created");
        }
        acn.setText("");
        am.setText("");
        }
        else if(bt==2){            
        int a=Integer.parseInt(acn.getText());
        boolean flag=true;
        for(int i=0;i<Bank.ba.size();i++)
        {
            if (a == Bank.ba.get(i).getAccount())
            { 
                AccountInfo af=new AccountInfo(Bank.ba.get(i),this);
                this.setVisible(false);
                af.setVisible(true);
                flag=false;
                break;
            }
        }
        if(flag==true){
            acc.setVisible(true);
            acc.setText("Account Not Present");
        }
        acn.setText("");
        }
        else if(bt==3){
        int a=Integer.parseInt(acn.getText());
        boolean flag=true;
        for(int i=0;i<Bank.ba.size();i++)
        {
            if (a == Bank.ba.get(i).getAccount())
            { 
                acc.setVisible(true);
                acc.setText("Account Balance : "+Bank.getInfo(a));                    
                flag=false;
                break;
            }
        }
        if(flag==true){
            acc.setVisible(true);
            acc.setText("Account Not Present");
        }
        acn.setText("");
        }
    }//GEN-LAST:event_proceedActionPerformed

    private void acnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acnActionPerformed

    }//GEN-LAST:event_acnActionPerformed

    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        
        acc.setVisible(false);
        acn.setVisible(true);
        am.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        proceed.setVisible(true);
        bt=1;
        
    }//GEN-LAST:event_addActionPerformed

    private void cdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdActionPerformed
        acc.setVisible(false);
        acn.setVisible(true);
        am.setVisible(false);
        jLabel2.setVisible(true);
        jLabel3.setVisible(false);
        proceed.setVisible(true);
        bt=2;        
    }//GEN-LAST:event_cdActionPerformed

    private void aiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aiActionPerformed
        acc.setVisible(false);
        acn.setVisible(true);
        am.setVisible(false);
        jLabel2.setVisible(true);
        jLabel3.setVisible(false);
        proceed.setVisible(true);
        bt=3; 
    }//GEN-LAST:event_aiActionPerformed

    private void tbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbActionPerformed
        acc.setVisible(true);
        acn.setVisible(false);
        am.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        proceed.setVisible(false);
        if(Bank.ba.size()==0){
            acc.setText("No Account Present In The Bank");
        }
        else
            acc.setText("Total Balance : "+Bank.getTotal());
    }//GEN-LAST:event_tbActionPerformed

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
        acc.setVisible(true);
        acn.setVisible(false);
        am.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        proceed.setVisible(false);
        
        if(Bank.ba.size()==0){
            acc.setText("No Account Present In The Bank");
        }
        else
            acc.setText("Minimum Balance Account : "+Bank.getMin()+"   Maximum Balance Account : "+Bank.getMax());
    }//GEN-LAST:event_mmActionPerformed

    private void mbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbaActionPerformed
        acc.setVisible(true);
        acn.setVisible(false);
        am.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        proceed.setVisible(false);
        if(Bank.ba.size()==0){
            acc.setText("No Account Present In The Bank");
        }
        else
            acc.setText("Total Account With Min Balance : "+Bank.count());
    }//GEN-LAST:event_mbaActionPerformed

    private void acnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acnMouseClicked
        acc.setText("");
    }//GEN-LAST:event_acnMouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc;
    private javax.swing.JTextField acn;
    private javax.swing.JButton add;
    private javax.swing.JButton ai;
    private javax.swing.JTextField am;
    private javax.swing.JButton cd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mba;
    private javax.swing.JButton mm;
    private javax.swing.JButton proceed;
    private javax.swing.JButton tb;
    // End of variables declaration//GEN-END:variables
}
